import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const extensionDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const shaderDir = resolve(extensionDir, 'shaders');
const outputPath = resolve(extensionDir, 'src/shaderSources.ts');

const shaders = [
  ['GLASS_FRAGMENT_SHADER', 'glass.frag'],
  ['BACKDROP_BLUR_FRAGMENT_SHADER', 'backdropBlur.frag'],
];

const definitions = await Promise.all(shaders.map(async ([exportName, filename]) => {
  const source = await readFile(resolve(shaderDir, filename), 'utf8');
  return `export const ${exportName} = ${JSON.stringify(source)};`;
}));

const output = `// Generated by scripts/build-shaders.mjs; do not edit manually.\n${definitions.join('\n')}\n`;
let existing = '';
try {
  existing = await readFile(outputPath, 'utf8');
} catch (error) {
  if (error?.code !== 'ENOENT') throw error;
}

if (existing !== output)
  await writeFile(outputPath, output);
